const reasons = [
"I love you because your beautiful eyes can brighten even the dullest day.",
"I love you because your smile has a way of making everything feel better.",
"I love you because your hair always looks beautiful to me.",
"I love you because your laugh is one of my favorite sounds.",
"I love you because your happiness makes me happy too.",
"I love you because you care deeply about the people you love.",
"I love you because your heart is pure and genuine.",
"I love you because your kindness shows in the little things you do.",
"I love you because talking to you never feels boring.",
"I love you because your bakbak can turn a bad day into a good one.",

"I love you because calling you Lakku feels so special.",
"I love you because you make ordinary moments memorable.",
"I love you because your voice brings me comfort.",
"I love you because you always stay true to yourself.",
"I love you because you make me feel understood.",
"I love you because your presence makes me feel at peace.",
"I love you because you notice details that others miss.",
"I love you because you make me laugh without even trying.",
"I love you because your excitement is contagious.",
"I love you because your honesty makes me trust you.",

"I love you because you listen when I need someone to listen.",
"I love you because you make me feel important.",
"I love you because your reactions are always genuine.",
"I love you because you make conversations feel effortless.",
"I love you because your energy makes life more enjoyable.",
"I love you because you always find a way to make me smile.",
"I love you because your caring nature makes people feel loved.",
"I love you because you make me look forward to every conversation.",
"I love you because your innocence is beautiful.",
"I love you because you are never afraid to be yourself.",

"I love you because your love for dal chawal is adorable.",
"I love you because you appreciate simple things in life.",
"I love you because you make me feel comfortable being myself.",
"I love you because your support means so much to me.",
"I love you because you remember small things about me.",
"I love you because your positivity is refreshing.",
"I love you because your personality is one of a kind.",
"I love you because you make every day a little brighter.",
"I love you because your compassion inspires me.",
"I love you because you always try to understand people.",

"I love you because your confidence is attractive.",
"I love you because your patience amazes me.",
"I love you because your sense of humor makes life fun.",
"I love you because you can find joy in small moments.",
"I love you because you make me feel appreciated.",
"I love you because your loyalty means everything.",
"I love you because your warmth makes people feel welcome.",
"I love you because you are thoughtful in ways that matter.",
"I love you because your smile stays in my mind long after I see it.",
"I love you because your presence can calm my worries.",

"I love you because you inspire me to be a better person.",
"I love you because your curiosity makes conversations interesting.",
"I love you because you are always willing to learn.",
"I love you because you never stop caring.",
"I love you because your encouragement gives me confidence.",
"I love you because you make me feel lucky.",
"I love you because you never pretend to be someone you're not.",
"I love you because your authenticity is rare.",
"I love you because you make ordinary conversations meaningful.",
"I love you because your optimism is inspiring.",

"I love you because you have a beautiful way of looking at life.",
"I love you because your dedication is admirable.",
"I love you because your empathy makes you special.",
"I love you because you understand emotions so well.",
"I love you because you make me feel safe emotionally.",
"I love you because you are always sincere.",
"I love you because you appreciate the people around you.",
"I love you because your laughter can light up a room.",
"I love you because your confidence helps others feel confident.",
"I love you because you never stop trying your best.",

"I love you because your determination inspires me.",
"I love you because you celebrate other people's successes.",
"I love you because you always try to see the good in people.",
"I love you because you make difficult days easier.",
"I love you because you are patient when it matters most.",
"I love you because you bring positivity wherever you go.",
"I love you because your kindness extends to everyone.",
"I love you because you value meaningful connections.",
"I love you because your honesty creates trust.",
"I love you because you have a beautiful soul.",

"I love you because your caring nature makes a difference.",
"I love you because you make me feel seen.",
"I love you because your support helps me grow.",
"I love you because your encouragement keeps me going.",
"I love you because your heart is full of love.",
"I love you because you make life more beautiful.",
"I love you because your words often bring comfort.",
"I love you because your presence feels like home.",
"I love you because you make me smile unexpectedly.",
"I love you because you have a way of making everything feel okay.",
"I love you because every day with you feels a little more special."
];
